from __future__ import annotations

"""Typing contracts for controller mixin dependencies."""

from pathlib import Path
from typing import Protocol

from portfolio_core.planning_types import PlanningMode

class MainWindowWelcomeDependencies(Protocol):

    def _quit_app(self) -> None: ...

    def _update_file_context_ui(self) -> None: ...

    def _open_portfolio_from_path(self, path: Path) -> bool: ...

    def _open_portfolio_from_picker(self) -> bool: ...

    def _load_default_document(self) -> None: ...


class MainWindowMainEditorDependencies(Protocol):

    def _on_save_clicked(self) -> None: ...

    def _on_save_as_clicked(self) -> None: ...

    def _on_open_clicked(self) -> None: ...

    def _on_new_clicked(self) -> None: ...

    def _normalize_future_tax_input(self) -> None: ...

    def _refresh_data(self) -> None: ...

    def _update_future_tax_visual_state(self) -> None: ...

    def _update_file_context_ui(self) -> None: ...

    def _run_planning(self, mode: PlanningMode) -> None: ...

    def _confirm_continue_with_unsaved_changes(self, action_text: str) -> bool: ...


class MainWindowSummaryDependencies(Protocol):

    def _quit_app(self) -> None: ...

    def _show_current_wizard_step(self) -> None: ...

    def _prepare_wizard_fx_rate_cache(self) -> None: ...
